// Code generated by mockery v2.33.0. DO NOT EDIT.

package coremocks

import mock "github.com/stretchr/testify/mock"

// Reply is an autogenerated mock type for the Reply type
type Reply struct {
	mock.Mock
}

// ReplyName provides a mock function with given fields:
func (_m *Reply) ReplyName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewReply creates a new instance of Reply. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReply(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reply {
	mock := &Reply{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
