// Code generated by mockery v2.33.0. DO NOT EDIT.

package coremocks

import mock "github.com/stretchr/testify/mock"

// SagaData is an autogenerated mock type for the SagaData type
type SagaData struct {
	mock.Mock
}

// SagaDataName provides a mock function with given fields:
func (_m *SagaData) SagaDataName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewSagaData creates a new instance of SagaData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSagaData(t interface {
	mock.TestingT
	Cleanup(func())
}) *SagaData {
	mock := &SagaData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
