// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import (
	context "context"

	core "github.com/rezaAmiri123/edat/core"
	mock "github.com/stretchr/testify/mock"

	msg "github.com/rezaAmiri123/edat/msg"
)

// CommandMessagePublisher is an autogenerated mock type for the CommandMessagePublisher type
type CommandMessagePublisher struct {
	mock.Mock
}

// PublisheCommand provides a mock function with given fields: ctx, replyChannel, command, options
func (_m *CommandMessagePublisher) PublisheCommand(ctx context.Context, replyChannel string, command core.Command, options ...msg.MessageOption) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, replyChannel, command)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, core.Command, ...msg.MessageOption) error); ok {
		r0 = rf(ctx, replyChannel, command, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommandMessagePublisher creates a new instance of CommandMessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommandMessagePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommandMessagePublisher {
	mock := &CommandMessagePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
