// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import mock "github.com/stretchr/testify/mock"

// DomainEvent is an autogenerated mock type for the DomainEvent type
type DomainEvent struct {
	mock.Mock
}

// DestinationChannel provides a mock function with given fields:
func (_m *DomainEvent) DestinationChannel() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// EventName provides a mock function with given fields:
func (_m *DomainEvent) EventName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewDomainEvent creates a new instance of DomainEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDomainEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *DomainEvent {
	mock := &DomainEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
