// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import (
	context "context"

	msg "github.com/rezaAmiri123/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// EntityEventHandlerFunc is an autogenerated mock type for the EntityEventHandlerFunc type
type EntityEventHandlerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *EntityEventHandlerFunc) Execute(_a0 context.Context, _a1 msg.EntityEvent) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, msg.EntityEvent) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEntityEventHandlerFunc creates a new instance of EntityEventHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntityEventHandlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntityEventHandlerFunc {
	mock := &EntityEventHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
