// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import (
	context "context"

	core "github.com/rezaAmiri123/edat/core"
	mock "github.com/stretchr/testify/mock"

	msg "github.com/rezaAmiri123/edat/msg"
)

// EntityEventMessagePublisher is an autogenerated mock type for the EntityEventMessagePublisher type
type EntityEventMessagePublisher struct {
	mock.Mock
}

// PublishEntityEvents provides a mock function with given fields: ctx, entity, options
func (_m *EntityEventMessagePublisher) PublishEntityEvents(ctx context.Context, entity core.Entity, options ...msg.MessageOption) error {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, entity)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, core.Entity, ...msg.MessageOption) error); ok {
		r0 = rf(ctx, entity, options...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEntityEventMessagePublisher creates a new instance of EntityEventMessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntityEventMessagePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntityEventMessagePublisher {
	mock := &EntityEventMessagePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
