// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import (
	msg "github.com/rezaAmiri123/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// EntityEventDispatcherOption is an autogenerated mock type for the EntityEventDispatcherOption type
type EntityEventDispatcherOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: consumer
func (_m *EntityEventDispatcherOption) Execute(consumer *msg.EntityEventDispatcher) {
	_m.Called(consumer)
}

// NewEntityEventDispatcherOption creates a new instance of EntityEventDispatcherOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntityEventDispatcherOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntityEventDispatcherOption {
	mock := &EntityEventDispatcherOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
