// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import (
	core "github.com/rezaAmiri123/edat/core"
	mock "github.com/stretchr/testify/mock"

	msg "github.com/rezaAmiri123/edat/msg"
)

// Event is an autogenerated mock type for the Event type
type Event struct {
	mock.Mock
}

// Event provides a mock function with given fields:
func (_m *Event) Event() core.Event {
	ret := _m.Called()

	var r0 core.Event
	if rf, ok := ret.Get(0).(func() core.Event); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Event)
		}
	}

	return r0
}

// Headers provides a mock function with given fields:
func (_m *Event) Headers() msg.Headers {
	ret := _m.Called()

	var r0 msg.Headers
	if rf, ok := ret.Get(0).(func() msg.Headers); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(msg.Headers)
		}
	}

	return r0
}

// NewEvent creates a new instance of Event. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *Event {
	mock := &Event{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
