// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import (
	msg "github.com/rezaAmiri123/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// MessageSubscriber is an autogenerated mock type for the MessageSubscriber type
type MessageSubscriber struct {
	mock.Mock
}

// Subscribe provides a mock function with given fields: channel, receiver
func (_m *MessageSubscriber) Subscribe(channel string, receiver msg.MessageReceiver) {
	_m.Called(channel, receiver)
}

// NewMessageSubscriber creates a new instance of MessageSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageSubscriber {
	mock := &MessageSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
