// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import mock "github.com/stretchr/testify/mock"

// MessageOption is an autogenerated mock type for the MessageOption type
type MessageOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: m
func (_m *MessageOption) Execute(m *msg.message) {
	_m.Called(m)
}

// NewMessageOption creates a new instance of MessageOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageOption {
	mock := &MessageOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
