// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import (
	context "context"

	msg "github.com/rezaAmiri123/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// MessagePublisher is an autogenerated mock type for the MessagePublisher type
type MessagePublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, message
func (_m *MessagePublisher) Publish(ctx context.Context, message msg.Message) error {
	ret := _m.Called(ctx, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, msg.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessagePublisher creates a new instance of MessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessagePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessagePublisher {
	mock := &MessagePublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
