// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import (
	msg "github.com/rezaAmiri123/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// PublisherOption is an autogenerated mock type for the PublisherOption type
type PublisherOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: publisher
func (_m *PublisherOption) Execute(publisher *msg.Publisher) {
	_m.Called(publisher)
}

// NewPublisherOption creates a new instance of PublisherOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPublisherOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *PublisherOption {
	mock := &PublisherOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
