// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import (
	core "github.com/rezaAmiri123/edat/core"
	mock "github.com/stretchr/testify/mock"

	msg "github.com/rezaAmiri123/edat/msg"
)

// Reply is an autogenerated mock type for the Reply type
type Reply struct {
	mock.Mock
}

// Headers provides a mock function with given fields:
func (_m *Reply) Headers() msg.Headers {
	ret := _m.Called()

	var r0 msg.Headers
	if rf, ok := ret.Get(0).(func() msg.Headers); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(msg.Headers)
		}
	}

	return r0
}

// Reply provides a mock function with given fields:
func (_m *Reply) Reply() core.Reply {
	ret := _m.Called()

	var r0 core.Reply
	if rf, ok := ret.Get(0).(func() core.Reply); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Reply)
		}
	}

	return r0
}

// NewReply creates a new instance of Reply. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReply(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reply {
	mock := &Reply{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
