// Code generated by mockery v2.33.0. DO NOT EDIT.

package msgmocks

import (
	msg "github.com/rezaAmiri123/edat/msg"
	mock "github.com/stretchr/testify/mock"
)

// SubscriberOption is an autogenerated mock type for the SubscriberOption type
type SubscriberOption struct {
	mock.Mock
}

// Execute provides a mock function with given fields: subscriber
func (_m *SubscriberOption) Execute(subscriber *msg.Subscriber) {
	_m.Called(subscriber)
}

// NewSubscriberOption creates a new instance of SubscriberOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSubscriberOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *SubscriberOption {
	mock := &SubscriberOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
